---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 15.02.2022 13:30
---


function JumpItem(xs, ys, item)
    local i = 0
    --local eff=ParticleManager:CreateParticle("particles\\units\\heroes\\hero_venomancer\\veno_tnt_banana_ground.vpcf",PATTACH_CUSTOMORIGIN,nil)
    Timers:CreateTimer(function()
        i = i + 1
        --print(i)
        --CreateItemOnPositionForLaunch(Vector(xs, ys, 128 + i * 2), item)
        --увы не работает
        if i >= 40 then
            --конец
        else
            return 1 / 64
        end
    end)

end